improving usage and testing

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,5 +1,9 @@
 #!/bin/sh
 
-echo "test if the TCP port ${SOFFICE_DAEMON_PORT} is open"
-TCP_PORT_STATUS=`(echo > /dev/tcp/127.0.0.1/8102) >/dev/null 2>&1 && echo "LISTENING at ${SOFFICE_DAEMON_PORT}" || echo "${SOFFICE_DAEMON_PORT} is closed"`
-echo $TCP_PORT_STATUS
+echo -e "\n\n test if the TCP port ${SOFFICE_DAEMON_PORT} is open"
+TCP_PORT_STATUS=`(echo > /dev/tcp/127.0.0.1/${SOFFICE_DAEMON_PORT}) >/dev/null 2>&1 && echo "LISTENING at Port ${SOFFICE_DAEMON_PORT}" || echo "Port ${SOFFICE_DAEMON_PORT} is closed"`
+echo -e "\t $TCP_PORT_STATUS"
+
+echo -e "\nyou can test a file conversion using the unoconv utility connecting to soffice running in this container."
+echo -e "\t put some .odt files into a dir on your host and them run the container attaching a volume:"
+echo -e "\n\t docker run -v ~/pdfs:/pdfs:rw rafaeltuelho/openoffice3-daemon unoconv --connection 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' -f pdf /pdfs/test.odt"
